// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: ba57474a08a42f8708812127521737bce088b300c1c4f6f8bd88984b144c9307


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "keycloak-theme";

export const themeNames: ThemeName[] = ["keycloak-theme"];

export type KcEnvName = "VITE_APP_NAME" | "VITE_APP_TAGLINE" | "VITE_APP_THEME" | "VITE_HOME_URL";

export const kcEnvNames: KcEnvName[] = ["VITE_APP_NAME", "VITE_APP_TAGLINE", "VITE_APP_THEME", "VITE_HOME_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "VITE_APP_NAME": "WormLabs",
  "VITE_APP_TAGLINE": "Build and deploy AI agents effortlessly.",
  "VITE_APP_THEME": "dark",
  "VITE_HOME_URL": "https://wormlabs.in"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
